[target.'cfg(any(target_arch = "xtensa", target_arch = "riscv"))']
runner = "espflash flash --monitor -L defmt -S"

[build]
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-Tdefmt.x"]

target = ["xtensa-esp32-none-elf", "xtensa-esp32s2-none-elf"]

[env]
SSID = ""

[unstable]
build-std = ["core", "alloc"]
