[package]
name = "foa_sta"
version = "0.2.0"
authors = ["Frostie314159 <frostie.neuenhausen@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "A station mode implementation for Ferris-on-Air."
homepage = "https://esp32-open-mac.be/"
repository = "https://github.com/esp32-open-mac/FoA"

[dependencies]
esp-config = { workspace = true }
esp-hal = { workspace = true }

embassy-futures = { workspace = true }
embassy-net-driver-channel = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }

foa = { version = "0.2.0", path = "../foa/" }

ethernet = { workspace = true }
heapless = { workspace = true }
llc-rs = { workspace = true }
embassy-net-driver = "0.2.0"

portable-atomic = { workspace = true }
ieee80211 = { workspace = true }
log = { workspace = true, optional = true }
defmt = { workspace = true, optional = true }
defmt-or-log = { workspace = true }
futures-util = { workspace = true }

[build-dependencies]
esp-config = { workspace = true, features = ["build"] }

[features]
default = ["alloc", "wpa2"]
rsn = ["ieee80211/crypto"]
wpa2 = ["rsn"]

alloc = []

esp32 = ["foa/esp32", "esp-hal/esp32"]
esp32s2 = ["foa/esp32s2", "esp-hal/esp32s2"]

log = ["dep:log", "foa/log", "defmt-or-log/log"]
# Connection metadata only; keeps handshake/key debug logs disabled.
connection-trace = ["log"]
defmt = ["dep:defmt", "defmt-or-log/defmt", "foa/defmt", "ieee80211/defmt"]
