[package]
name = "foa_sta"
version = "0.1.1"
authors = ["Frostie314159 <frostie.neuenhausen@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "A station mode implementation for Ferris-on-Air."
homepage = "https://esp32-open-mac.be/"
repository = "https://github.com/esp32-open-mac/FoA"

[dependencies]
defmt = { version = "1.0.1", optional = true }
defmt-or-log = { version = "0.2.3", default-features = false }
embassy-futures = "0.1.2"
embassy-net-driver-channel = "0.4.0"
embassy-sync = "0.8.0"
embassy-time = "0.5.1"
esp-config = "0.6.1"
ethernet = { version = "0.1.6", default-features = false }
foa = { version = "0.1.0", path = "../foa/" }
heapless = "0.9.1"
llc-rs = "0.1.1"
portable-atomic = "1.11.1"
ieee80211 = "0.5.9"
log = { version = "0.4.28", optional = true }
futures-util = { version = "0.3.32", default-features = false }
esp-hal = { version = "1.0.0", default-features = false }
embassy-net-driver = "0.2.0"

[build-dependencies]
esp-config = { version = "0.6.1", features = ["build"] }

[features]
default = ["wpa2"]
rsn = ["ieee80211/crypto"]
wpa2 = ["rsn"]

esp32 = ["foa/esp32", "esp-hal/esp32"]
esp32s2 = ["foa/esp32s2", "esp-hal/esp32s2"]

log = ["dep:log", "foa/log", "defmt-or-log/log"]
defmt = ["dep:defmt", "defmt-or-log/defmt", "foa/defmt", "ieee80211/defmt"]
