[package]
name = "examples"
version = "0.1.0"
authors = ["Frostie314159 <frostie.neuenhausen@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { workspace = true }
esp-rtos = { version = "0.3.0", features = ["embassy"] }
esp-backtrace = { version = "0.19.0", features = ["panic-handler", "println"] }
esp-println = { version = "0.17.0", features = [
    "defmt-espflash",
    "critical-section",
    "uart",
], default-features = false }

embassy-net = { version = "0.9.1", features = [
    "proto-ipv4",
    "proto-ipv6",
    "dhcpv4",
    "multicast",
    "slaac",
    "auto-icmp-echo-reply",
    "medium-ethernet",
    "tcp",
    "udp",
    "dns",
] }
embassy-futures = { version = "0.1.2"}
embassy-time = { version = "0.5.1" }
embassy-executor = { version = "0.10.0" }

foa = { path = "../foa" }
foa_sta = { path = "../foa_sta", features = ["alloc"] }
foa_awdl = { path = "../foa_awdl" }

static_cell = "2.1.1"
heapless = "0.9.3"
embedded-io-async = "0.7.0"

reqwless = { version = "0.14.0", default-features = false }
# esp-mbedtls = { git = "https://github.com/esp-rs/esp-mbedtls.git", default-features = false,  }
embedded-io = "0.7.1"
esp-alloc = "0.10.0"
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp-rom-sys"] }
embassy-sync = "0.8.0"
log.workspace = true


[features]
esp32 = [
    "esp-hal/esp32",
    "esp-rtos/esp32",
    "esp-println/esp32",
    "esp-backtrace/esp32",
    "esp-bootloader-esp-idf/esp32",
    "foa/esp32",
    "foa_sta/esp32",
    "foa_awdl/esp32",
]
esp32s2 = [
    "esp-hal/esp32s2",
    "esp-rtos/esp32s2",
    "esp-println/esp32s2",
    "esp-bootloader-esp-idf/esp32s2",
    "esp-backtrace/esp32s2",
    "foa/esp32s2",
    "foa_sta/esp32s2",
    "foa_awdl/esp32s2",
]
