[package]
name = "foa_awdl"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-futures = { workspace = true }
embassy-net-driver-channel = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }

foa = { version = "0.2.0", path = "../foa/" }
heapless = { workspace = true }
esp-config = { workspace = true }
llc-rs = { workspace = true }
ethernet = { workspace = true, default-features = false }
ether-type = "0.1.5"
smoltcp = { version = "0.13.0", default-features = false, features = [
  "medium-ethernet",
  "proto-ipv6",
  "socket-raw",
] }
awdl-frame-parser = "0.4.1"
ieee80211 = { workspace = true }
log = { workspace = true, optional = true }
defmt = { workspace = true, optional = true }
defmt-or-log = { workspace = true }
esp-hal = { workspace = true }

[build-dependencies]
esp-config = { workspace = true, features = ["build"] }

[features]
alloc = []
esp32 = ["foa/esp32"]
esp32s2 = ["foa/esp32s2"]

defmt = ["dep:defmt", "defmt-or-log/defmt", "ieee80211/defmt", "foa/defmt"]
log = ["dep:log", "foa/log", "defmt-or-log/log"]

ndp-inject = []
default = ["ndp-inject"]
