crate: foa_awdl

options:
  - name: peer_cache_size
    description: The maximum number of peers that can be cached.
    default:
      - value: 4
    constraints:
      - type:
          validator: positive_integer
  - name: net_tx_buffers
    description: The amount of TX buffers used for embassy_net_driver_channel.
    default:
      - value: 4
    constraints:
      - type:
          validator: positive_integer
  - name: net_rx_buffers
    description: The amount of RX buffers used for embassy_net_driver_channel.
    default:
      - value: 4
    constraints:
      - type:
          validator: positive_integer
  - name: event_queue_depth
    description: The maximum number of events, that the event queue can hold
    default:
      - value: 4
    constraints:
      - type:
          validator: positive_integer
